services:
  app:
    image: whale-alert:latest
    container_name: whale-alert
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=UTC
    tty: true  # Enable TTY for OTP input
    stdin_open: true  # Keep STDIN open for interactive input
    volumes:
      - ./.env:/app/.env
      - telegram-session:/app/whale_alert/telegram/sessions  # Persist Telegram session
    networks:
      - whale-alert-net

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  whale-alert-net:
    external: true

volumes:
  telegram-session:  # Named volume for persisting Telegram session