services:
  app:
    image: whale-alert:latest
    container_name: whale-alert
    restart: unless-stopped
    env_file: .env
    environment:
      - TZ=UTC
    tty: true
    stdin_open: true
    volumes:
      - ./.env:/app/.env
      - ./sessions:/app/sessions
    networks:
      - whale-alert-net

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  whale-alert-net:
    external: true